[experiment]
method = "fedavgm"
task = "cifar10_cnn"
seeds = [1337, 1338, 1339]

[server]
num-server-rounds = 20
fraction-train = 1.0
fraction-evaluate = 1.0
min-available-nodes = 24
min-train-nodes = 24
min-evaluate-nodes = 24
capability-discovery-timeout-s = 120.0

[client]
local-epochs = 1
learning-rate = 0.01
batch-size = 32

[data]
partitioning = "iid"
partitioning-num-labels = 2
partitioning-dirichlet-alpha = 0.1
masked-cross-entropy = "auto"

[model]
global-model-rate = 1.0
default-model-rate = 1.0

[fedavgm]
server-momentum = 0.9

[evaluation]
client-eval-enabled = false
final-client-eval-enabled = true

[wandb]
enabled = true
group = "network_heterogeneity-scale_async-cifar10_cnn"
tags = ["network_heterogeneity", "scale_async", "cifar10_cnn", "fedavgm", "c24"]

[devices.rpi4]
model-rate = 1.0
batch-size = 8
max-train-examples = 2048
max-test-examples = 512

[devices.rpi5]
model-rate = 1.0
batch-size = 32
max-train-examples = 8192
max-test-examples = 2048
