# Existing cluster
[nomad_servers]
rpi1 ansible_host=192.168.8.101 ansible_user=rpi1

[submit_service]
rpi1

[nomad_submit_clients]
rpi2 ansible_host=192.168.8.102 ansible_user=rpi2 nomad_node_class=submit nomad_device_type=submit nomad_enable_docker_socket=true

# Additional 20 RPis
# 2 submit nodes
rpi5 ansible_host=192.168.8.105 ansible_user=rpi5 nomad_node_class=submit nomad_device_type=submit nomad_enable_docker_socket=true
rpi6 ansible_host=192.168.8.106 ansible_user=rpi6 nomad_node_class=submit nomad_device_type=submit nomad_enable_docker_socket=true

[nomad_superlink_clients]
rpi3 ansible_host=192.168.8.103 ansible_user=rpi3 nomad_node_class=link nomad_device_type=link

# 3 superlink nodes
rpi7 ansible_host=192.168.8.107 ansible_user=rpi7 nomad_node_class=link nomad_device_type=link
rpi8 ansible_host=192.168.8.108 ansible_user=rpi8 nomad_node_class=link nomad_device_type=link
rpi9 ansible_host=192.168.8.109 ansible_user=rpi9 nomad_node_class=link nomad_device_type=link

[nomad_supernode_clients]
rpi4 ansible_host=192.168.8.104 ansible_user=rpi4 nomad_node_class=node nomad_device_type=rpi

# 15 supernode nodes
rpi10 ansible_host=192.168.8.110 ansible_user=rpi10 nomad_node_class=node nomad_device_type=rpi
rpi11 ansible_host=192.168.8.111 ansible_user=rpi11 nomad_node_class=node nomad_device_type=rpi
rpi12 ansible_host=192.168.8.112 ansible_user=rpi12 nomad_node_class=node nomad_device_type=rpi
rpi13 ansible_host=192.168.8.113 ansible_user=rpi13 nomad_node_class=node nomad_device_type=rpi
rpi14 ansible_host=192.168.8.114 ansible_user=rpi14 nomad_node_class=node nomad_device_type=rpi
rpi15 ansible_host=192.168.8.115 ansible_user=rpi15 nomad_node_class=node nomad_device_type=rpi
rpi16 ansible_host=192.168.8.116 ansible_user=rpi16 nomad_node_class=node nomad_device_type=rpi
rpi17 ansible_host=192.168.8.117 ansible_user=rpi17 nomad_node_class=node nomad_device_type=rpi
rpi18 ansible_host=192.168.8.118 ansible_user=rpi18 nomad_node_class=node nomad_device_type=rpi
rpi19 ansible_host=192.168.8.119 ansible_user=rpi19 nomad_node_class=node nomad_device_type=rpi
rpi20 ansible_host=192.168.8.120 ansible_user=rpi20 nomad_node_class=node nomad_device_type=rpi
rpi21 ansible_host=192.168.8.121 ansible_user=rpi21 nomad_node_class=node nomad_device_type=rpi
rpi22 ansible_host=192.168.8.122 ansible_user=rpi22 nomad_node_class=node nomad_device_type=rpi
rpi23 ansible_host=192.168.8.123 ansible_user=rpi23 nomad_node_class=node nomad_device_type=rpi
rpi24 ansible_host=192.168.8.124 ansible_user=rpi24 nomad_node_class=node nomad_device_type=rpi

[nomad_clients:children]
nomad_submit_clients
nomad_superlink_clients
nomad_supernode_clients
