---
nomad_client_enable_docker: true
nomad_client_enable_docker_socket: false

nomad_docker_allow_caps:
  - "audit_write"
  - "chown"
  - "dac_override"
  - "fowner"
  - "fsetid"
  - "kill"
  - "mknod"
  - "net_admin"
  - "net_bind_service"
  - "net_raw"
  - "setfcap"
  - "setgid"
  - "setpcap"
  - "setuid"
  - "sys_chroot"

docker_image_cleanup_enabled: true
docker_image_cleanup_node_classes:
  - "submit"
docker_image_cleanup_until: "24h"
docker_image_cleanup_schedule: "04:00"
