---
- name: Configure Nomad server nodes
  hosts: nomad_servers
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/nomad_servers.yml
  roles:
    - role: nomad
      nomad_role: server
