---
- name: Configure Nomad client nodes
  hosts: nomad_clients
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/nomad_clients.yml
  roles:
    - role: nomad
      nomad_role: client
