---
- name: Configure Docker cleanup on submit clients
  hosts: nomad_submit_clients
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/nomad_clients.yml
  roles:
    - role: docker
