---
- import_playbook: playbooks/network_policy.yml
- import_playbook: playbooks/base_system.yml
- import_playbook: playbooks/tailscale.yml
- import_playbook: playbooks/nomad_server.yml
- import_playbook: playbooks/docker.yml
- import_playbook: playbooks/registry.yml
- import_playbook: playbooks/nomad_client.yml
- import_playbook: playbooks/submit_service.yml
- import_playbook: playbooks/validate.yml
