---
submit_repo_url: "git@github.com:Haoran-Jie/fedctl.git"
submit_repo_version: "main"
submit_repo_dir: "/opt/fedctl"
submit_venv_path: "/opt/fedctl/.venv"
submit_db_url: "sqlite:////opt/fedctl/submit_service/state/submit.db"
submit_dispatch_mode: "queue"
submit_autopurge_completed_after_s: 0
submit_presign_ttl: 86400
submit_allow_unauth: false
submit_bind_host: "0.0.0.0"
submit_bind_port: 8080
submit_ui_enabled: false
submit_ui_session_secret: ""
submit_ui_cookie_name: "fedctl_submit_session"
submit_ui_cookie_secure: false
submit_aws_shared_credentials_file: ""
submit_aws_config_file: ""
submit_aws_profile: ""
submit_aws_region: ""
submit_aws_credentials_src: ""
submit_aws_config_src: ""
submit_tokens: []
submit_repo_config_path: "/etc/fedctl/cluster-fedctl.yaml"
submit_legacy_repo_config_path: "{{ submit_repo_dir }}/.fedctl/fedctl.yaml"
submit_cluster_repo_config:
  deploy:
    placement:
      allow_oversubscribe: true
    resources:
      superexec_clientapp:
        cpu: 2000
        mem: 2048
      superexec_serverapp:
        cpu: 2000
        mem: 2048
      superlink:
        cpu: 1000
        mem: 1024

submit_nomad_endpoint: >-
  http://{{ hostvars[groups['nomad_servers'][0]].cluster_node_ip | default(hostvars[groups['nomad_servers'][0]].ansible_host) }}:4646
