[experiment]
method = "fedavg"
task = "cifar10_cnn"
seeds = [1337, 1338, 1339]

[server]
num-server-rounds = 20
fraction-train = 1.0
fraction-evaluate = 1.0
min-available-nodes = 20
min-train-nodes = 20
min-evaluate-nodes = 20
capability-discovery-timeout-s = 180.0

[client]
local-epochs = 3
learning-rate = 0.05
batch-size = 32

[data]
partitioning = "iid"
partitioning-num-labels = 2
partitioning-dirichlet-alpha = 0.1
masked-cross-entropy = "auto"

[model]
global-model-rate = 1.0
default-model-rate = 1.0

[capacity]
model-split-mode = "fix"
model-rate-levels = [1.0, 0.5, 0.25, 0.125]
model-rate-proportions = [0.25, 0.25, 0.25, 0.25]

[wandb]
enabled = true
group = "compute_heterogeneity-main-cifar10_cnn"
tags = ["compute_heterogeneity", "main", "cifar10_cnn", "fedavg", "iid"]

[devices.rpi4]
model-rate = 1.0
batch-size = 8
max-train-examples = 2500
max-test-examples = 500

[devices.rpi5]
model-rate = 1.0
batch-size = 32
max-train-examples = 2500
max-test-examples = 500
